name: Automatic Approve
description: Automatically approve workflow runs from first time contributors
runs:
  using: node12
  main: index.js
branding:
  icon: user-check
  color: green
inputs:
  token:
    description: The GitHub Token to use
    required: true
  workflows:
    description: The workflows to automatically approve
    required: true
  dangerous_files:
    description: Filenames that prevent the PR being automatically approved
    required: false

